export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const LOAD_NEW_LIST_TABLE_DATA = 'LOAD_NEW_LIST_TABLE_DATA';
export const CHANGE_NEW_LIST_TABLE_DATA = 'CHANGE_NEW_LIST_TABLE_DATA';
export const DELETE_NEW_LIST_TABLE_DATA = 'DELETE_NEW_LIST_TABLE_DATA';
